name: Create Tag & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get versions
        id: get_version
        run: |
          echo github.actor
          version=$(echo '${{ github.event.head_commit.message }}' | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          if [[ -z "$version" ]]; then
            echo "No valid version found in commit message" >&2
            exit 1
          fi
          echo "version=v$version" >> $GITHUB_OUTPUT
      - name: make release
        uses: initia-labs/actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
